### ISSUE TITLE
Technical viability of the solutions

### ISSUE THREAD

**Issue by VishalG94** [SJSUFall2019-CMPE272/Virtual-Yoga-Trainer#1]
It happens sometimes that a single picture might not be adequate to analyze the yoga posture and confirm if it’s the right form or not. It might require more data to further validate and provide a feedback with higher accuracy to the user. So, how exactly will the user data be provided to the ML mode, will you be providing a stream of images as an input or a single image to detect the accuracy of the posture.

**Comment by harshrajm** [comment]
As our application deals in providing pose correctness score for a live video stream from webcam. So, We judge the pose correctness value for multiple frames than just a single frame.
