### ISSUE TITLE
How will the application provide feedback to it's users?

### ISSUE THREAD

**Issue by VishalG94** [SJSUFall2019-CMPE272/Virtual-Yoga-Trainer#2]
Will the app be able to spot exactly where the posture need to be improved, and provide any feedback on how it could be improved. Will the app be able to provide a feedback by highlighting a specific region in the user photo so that they could have a reference on what exactly needs to be done to improve the posture.

**Comment by harshrajm** [comment]
The app features a progress bar to show the correctness of the entire pose. This correctness value is calculated by using 17 data points which corresponds to various body parts.
